AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Application for integrating Thetis IMS with e-conomic
Metadata:
  AWS::ServerlessRepo::Application:
    Name: thetis-ims-economic-accounting
    Description: Application for accounting from Thetis IMS in e-conomic
    Author: thetis-apps
    SpdxLicenseId: Apache-2.0
    LicenseUrl: s3://aws-sam-cli-managed-default-samclisourcebucket-1q52gionhjeg3/4612b8d5aa75b9b9936c9b7b9e6c7e82
    ReadmeUrl: s3://aws-sam-cli-managed-default-samclisourcebucket-1q52gionhjeg3/6897102163965750d58f01f4be0b3d89
    Labels:
    - thetis-ims
    HomePageUrl: https://github.com/thetis-apps/EconomicAccounting
    SemanticVersion: 1.1.1
    SourceCodeUrl: https://github.com/thetis-apps/EconomicAccounting
Globals:
  Function:
    Runtime: nodejs16.x
    MemorySize: 512
    Timeout: 60
Parameters:
  ContextId:
    Type: String
    Description: Context that this application is handling events for.
    MinLength: 1
  ClientId:
    Description: Key of the parameter that has your Thetis client id as its value.
    Type: AWS::SSM::Parameter::Value<String>
    Default: ThetisClientId
  ClientSecret:
    Description: Key of the parameter that has your Thetis client secret as its value.
    Type: AWS::SSM::Parameter::Value<String>
    Default: ThetisClientSecret
  WebAcl:
    Description: Key of the parameter that has a WAF to use for publicly exposed endpoints
      as its value
    Type: AWS::SSM::Parameter::Value<String>
    Default: ThetisWebAcl
  ApiKey:
    Description: The api key that gives access to the context in Thetis IMS.
    Type: String
    MinLength: 1
  DevOpsEmail:
    Description: The email address to send mail to when messages in the dead letter
      queue.
    Type: String
    MinLength: 4
Resources:
  DocumentHandler:
    Type: AWS::Serverless::Function
    Properties:
      Description: Function that runs when a relevant document is created within Thetis
        IMS
      Handler: src/app.documentHandler
      Environment:
        Variables:
          ClientId:
            Ref: ClientId
          ClientSecret:
            Ref: ClientSecret
          ApiKey:
            Ref: ApiKey
          ContextId:
            Ref: ContextId
      Events:
        Request:
          Type: EventBridgeRule
          Properties:
            Pattern:
              source:
              - public.thetis-ims.com
              detail-type:
              - documentCreated
              detail:
                documentType:
                - GOODS_RECEIPT
                - COST_OF_SALES_LIST
                - ADJUSTMENT_LIST
                - COST_VARIANCE_LIST
                - VALUE_ADJUSTMENT_RECEIPT
                contextId:
                - Ref: ContextId
      Timeout: 100
      DeadLetterQueue:
        Type: SQS
        TargetArn:
          Fn::GetAtt:
          - DeadLetterQueue
          - Arn
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-1q52gionhjeg3/25c8e103ac488087777d053b674f3b36
    Metadata:
      SamResourceId: DocumentHandler
  InitResource:
    Type: AWS::CloudFormation::CustomResource
    Properties:
      ServiceToken:
        Fn::GetAtt:
        - InitializeFunction
        - Arn
      Version: 1
    Metadata:
      SamResourceId: InitResource
  InitializeFunction:
    Type: AWS::Serverless::Function
    DeletionPolicy: Delete
    Properties:
      Handler: src/app.initializer
      MemorySize: 2048
      Timeout: 30
      Environment:
        Variables:
          ClientId:
            Ref: ClientId
          ClientSecret:
            Ref: ClientSecret
          ApiKey:
            Ref: ApiKey
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-1q52gionhjeg3/25c8e103ac488087777d053b674f3b36
    Metadata:
      SamResourceId: InitializeFunction
  DeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      KmsMasterKeyId: alias/aws/sqs
    Metadata:
      SamResourceId: DeadLetterQueue
